name: Create and deploy Azure serverless-app

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: write

env:
  # AZURE_FUNCTIONAPP_NAME: github.repository_name 
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/functions' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          npm install -g azure-functions-core-tools@3 --unsafe-perm true

          # npm run build --if-present
          # npm run test --if-present
          popd

      - name: 'Login to Azure'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    
        
        run: | 
         az login --use-device-code
         
      - name: 'Create a resource group'
        run: |
          az group create --name AzureFunctionsQuickstart-rg --location westus
          
      - name: 'Create Azure Storage'
        run: |
          az storage account create --name ${ --location westus --resource-group AzureFunctionsQuickstart-rg --sku Standard_LRS --allow-blob-public-access false


      - name: 'Create Azure Function app'
        run: |
          az functionapp create --resource-group AzureFunctionsQuickstart-rg --consumption-plan-location westus --runtime node --runtime-version 20 --functions-version 4 --name ${{github.repository_name }} --storage-account stowre
 
 
      # - name: 'Run Azure Functions Action'
      #   uses: Azure/functions-action@v1
         
      #   with:
      #   app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      #   package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
      #   publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
